name: Python CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      # ---- Source ----
      - name: Checkout code
        uses: actions/checkout@v3

      # ---- Build ----
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ---- Test ----
      - name: Run Tests with Pytest
        run: pytest --maxfail=1 --disable-warnings -q

      # ---- Staging ----
      - name: Build Docker Image
        run: docker build -t python-cicd-app:staging .

      # ---- Deploy ----
      - name: Deploy to AWS EC2
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.AWS_EC2_IP }} "
          docker stop python-cicd-app || true &&
          docker rm python-cicd-app || true &&
          docker run -d --name python-cicd-app -p 80:5000 python-cicd-app:staging
          "
